theme:
  colorScheme: "#f9abff"
  layout: auto # dark | light | auto

favicon: "/avatar.png" # path( or url) of avatar such as /favicon.png

# Navigation Drawer 导航栏
drawer:
  always_open: false
  # true - if you open it once, it will open all the time util you close it 打开了就会一直打开
  # false - open when you click the menu button, won't open when page loads 关闭，点击按钮才打开
  menu: # add your entries here 在此处添加您的条目
   主页: # display text for "home page"
      icon: home # mdui icon
      url: /
      home: true
   分类: # catorgories
      icon: folder
      url: /categories
   标签: # tags
      icon: bookmark
      url: /tags
   帖子: # archives
      icon: archive
      url: /archives
   关于: # about
      icon: info
      url: /about

copyright: ""

# supports twikoo comment system
# see: https://twikoo.js.org/frontend.html
# this way only supports v0.2.0-beta, move to "comment" instead
# twikoo: 
#   enable: false
#   cdn: /js/twikoo.all.min.js # or use cdn such as https://cdn.bootcdn.net/ajax/libs/twikoo/1.6.31/twikoo.all.min.js
#   # twikoo settings:
#   envId: ""
#   region: '' 
#   path: location.pathname # will eval this, be careful
#   lang: 'zh-CN' 

comment:
  system: twikoo # none | twikoo | gitalk | waline
  twikoo:  # see: https://twikoo.js.org/frontend.html
    cdn: 
      js: /js/twikoo.all.min.js # or use cdn such as https://cdn.bootcdn.net/ajax/libs/twikoo/1.6.31/twikoo.all.min.js
    
    # twikoo settings:
    envId: "https://twikoo.006.tobylai.fun/"
    region: '' # region, see twikoo documentation
    path: location.pathname # will eval this, be careful
    lang: 'zh-CN' 
  gitalk: # see https://github.com/gitalk/gitalk
    cdn:
      css: /css/gitalk.css
      js: /js/gitalk.min.js

    # gitalk settings:
    clientID: '' # GitHub Application Client ID
    clientSecret: '' # GitHub Application Client Secret
    repo: '' # GitHub repo
    owner: '' # GitHub repo owner
    admin: [] # GitHub repo owner and collaborators, only these guys can initialize github issues
    id: decodeURIComponent(location.pathname)# will eval this, be careful
    # this is like /2024/01/24/xxxxxxxxxx ,make sure the length < 50
    # Ensure uniqueness and length less than 50
    distractionFreeMode: false  # Facebook-like distraction free mode
    #proxy: 
    # you may need a reverse proxy to support cors, default url may not work in some places(such as cn)
  waline:
    cdn:
      css: /css/waline.css
      js: /js/waline.js
    serverURL: ""

# display in the card at the top of the page under the subtitle
display_index_top:
  text: "dev-mdsuper"
  avatar: "" # path( or url) of avatar such as /avatar.png

# assets
mdui:
  css: /css/mdui_2.0.3/mdui.css
  js: /css/mdui_2.0.3/mdui.global.js

# install https://github.com/wzpan/hexo-generator-search and configure it following the readme
search:
  enable: false
  xml: /search.xml # only supports xml